"""empty message

Revision ID: 1719484b5347
Revises: 9115a6aced2b
Create Date: 2021-04-12 13:02:57.846441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1719484b5347'
down_revision = '9115a6aced2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('post_id', sa.String(), nullable=True))
    op.drop_index('ix_posts_photo_path', table_name='posts')
    op.drop_index('ix_posts_text', table_name='posts')
    op.create_index(op.f('ix_posts_post_id'), 'posts', ['post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_post_id'), table_name='posts')
    op.create_index('ix_posts_text', 'posts', ['text'], unique=False)
    op.create_index('ix_posts_photo_path', 'posts', ['photo_path'], unique=False)
    op.drop_column('posts', 'post_id')
    # ### end Alembic commands ###
