"""empty message

Revision ID: 1b79e4111413
Revises: 1719484b5347
Create Date: 2021-04-12 14:39:03.640466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b79e4111413'
down_revision = '1719484b5347'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('photo', sa.String(), nullable=True))
    op.drop_index('ix_reviews_email', table_name='reviews')
    op.drop_index('ix_reviews_name', table_name='reviews')
    op.drop_index('ix_reviews_review', table_name='reviews')
    op.create_index(op.f('ix_reviews_photo'), 'reviews', ['photo'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_photo'), table_name='reviews')
    op.create_index('ix_reviews_review', 'reviews', ['review'], unique=False)
    op.create_index('ix_reviews_name', 'reviews', ['name'], unique=False)
    op.create_index('ix_reviews_email', 'reviews', ['email'], unique=False)
    op.drop_column('reviews', 'photo')
    # ### end Alembic commands ###
