"""empty message

Revision ID: 2e98237cafb4
Revises: c56940a9fdd3
Create Date: 2021-04-09 13:24:16.596623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e98237cafb4'
down_revision = 'c56940a9fdd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_file_file_path'), 'file', ['file_path'], unique=False)
    op.create_index(op.f('ix_file_name'), 'file', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_name'), table_name='file')
    op.drop_index(op.f('ix_file_file_path'), table_name='file')
    # ### end Alembic commands ###
