"""empty message

Revision ID: 9115a6aced2b
Revises: f57ad9ee5302
Create Date: 2021-04-11 16:24:18.905460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9115a6aced2b'
down_revision = 'f57ad9ee5302'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mails_email', table_name='mails')
    op.create_index(op.f('ix_mails_email'), 'mails', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mails_email'), table_name='mails')
    op.create_index('ix_mails_email', 'mails', ['email'], unique=1)
    # ### end Alembic commands ###
