"""empty message

Revision ID: 921a7b331d91
Revises: 1b79e4111413
Create Date: 2021-04-14 18:43:08.380786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '921a7b331d91'
down_revision = '1b79e4111413'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('flag_to_post', sa.String(length=1), nullable=True))
    op.create_index(op.f('ix_reviews_flag_to_post'), 'reviews', ['flag_to_post'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_flag_to_post'), table_name='reviews')
    op.drop_column('reviews', 'flag_to_post')
    # ### end Alembic commands ###
